/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxE1APid (65535)
#define maxF1APid (4)
#define maxEARFCN (65535)
#define maxNRARFCN (3279165)
#define maxnoofNrCellBands (32)
#define maxnoofCells (16384)
#define maxnoofRICStyles (63)
#define maxnoofMeasurementInfo (65535)
#define maxnoofLabelInfo (2147483647)
#define maxnoofMeasurementRecord (65535)
#define maxnoofMeasurementValue (2147483647)
#define maxnoofConditionInfo (32768)
#define maxnoofUEID (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
