/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "kpmv2.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_MeasurementCondUEidItem_H_
#define	_MeasurementCondUEidItem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MeasurementType.h"
#include "MatchingCondList.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MatchingUEidList;

/* MeasurementCondUEidItem */
typedef struct MeasurementCondUEidItem {
	MeasurementType_t	 measType;
	MatchingCondList_t	 matchingCond;
	struct MatchingUEidList	*matchingUEidList;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCondUEidItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCondUEidItem;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementCondUEidItem_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementCondUEidItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementCondUEidItem_H_ */
#include "asn_internal.h"
