/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e2ap-container-v03.01.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /tmp/workspace/tuan1/`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using RICaction_ToBeSetup_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_Admitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_NotAdmitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscription_withCause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_AddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdateRemove_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionSetupFailed_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAddition_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeTNLassociationRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAdditionAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdateAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemovalAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunction_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionID_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionIDcause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeSetup_ItemIEs_1,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeSetup_ItemIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P1_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_Admitted_ItemIEs_5,
	3,	/* Elements count */
	&asn_SPC_RICaction_Admitted_ItemIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P2_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_NotAdmitted_ItemIEs_9,
	3,	/* Elements count */
	&asn_SPC_RICaction_NotAdmitted_ItemIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P3_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscription_withCause_ItemIEs_13,
	3,	/* Elements count */
	&asn_SPC_RICsubscription_withCause_ItemIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P4_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeRemovedForModification_ItemIEs_17,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeRemovedForModification_ItemIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P5_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeModifiedForModification_ItemIEs_21,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeModifiedForModification_ItemIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P6_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeAddedForModification_ItemIEs_25,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeAddedForModification_ItemIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P7_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RemovedForModification_ItemIEs_29,
	3,	/* Elements count */
	&asn_SPC_RICaction_RemovedForModification_ItemIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P8_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeRemovedForModification_ItemIEs_33,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeRemovedForModification_ItemIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P9_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ModifiedForModification_ItemIEs_37,
	3,	/* Elements count */
	&asn_SPC_RICaction_ModifiedForModification_ItemIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P10_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeModifiedForModification_ItemIEs_41,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeModifiedForModification_ItemIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P11_tags_12[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_AddedForModification_ItemIEs_45,
	3,	/* Elements count */
	&asn_SPC_RICaction_AddedForModification_ItemIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P12_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeAddedForModification_ItemIEs_49,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeAddedForModification_ItemIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P13_tags_14[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RequiredToBeModified_ItemIEs_53,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeModified_ItemIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P14_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RequiredToBeRemoved_ItemIEs_57,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeRemoved_ItemIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P15_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ConfirmedForModification_ItemIEs_61,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForModification_ItemIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P16_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RefusedToBeModified_ItemIEs_65,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeModified_ItemIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P17_tags_18[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ConfirmedForRemoval_ItemIEs_69,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForRemoval_ItemIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P18_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RefusedToBeRemoved_ItemIEs_73,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeRemoved_ItemIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P19_tags_20[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionUpdate_ItemIEs_77,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdate_ItemIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P20_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionUpdateRemove_ItemIEs_81,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdateRemove_ItemIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P21_tags_22[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionSetupFailed_ItemIEs_85,
	3,	/* Elements count */
	&asn_SPC_E2connectionSetupFailed_ItemIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P22_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigAddition_ItemIEs_89,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAddition_ItemIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P23_tags_24[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigUpdate_ItemIEs_93,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdate_ItemIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P24 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P24_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigRemoval_ItemIEs_97,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemoval_ItemIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P25 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P25_tags_26[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeTNLassociationRemoval_ItemIEs_101,
	3,	/* Elements count */
	&asn_SPC_E2nodeTNLassociationRemoval_ItemIEs_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P26 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P26_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigAdditionAck_ItemIEs_105,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAdditionAck_ItemIEs_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P27 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P27_tags_28[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigUpdateAck_ItemIEs_109,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdateAck_ItemIEs_specs_109	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P28 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P28_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigRemovalAck_ItemIEs_113,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemovalAck_ItemIEs_specs_113	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P29 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P29_tags_30[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunction_ItemIEs_117,
	3,	/* Elements count */
	&asn_SPC_RANfunction_ItemIEs_specs_117	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P30 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P30_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionID_ItemIEs_121,
	3,	/* Elements count */
	&asn_SPC_RANfunctionID_ItemIEs_specs_121	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_88P31 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_88P31_tags_32[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionIDcause_ItemIEs_125,
	3,	/* Elements count */
	&asn_SPC_RANfunctionIDcause_ItemIEs_specs_125	/* Additional specs */
};

